version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env